apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-micro-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-micro
  template:
    metadata:
      labels:
        app: simple-micro
    spec:
      containers:
        - name: simple-micro
          image: 56715/simple-micro
          env:
            - name: MONGO_URI
              value: 'mongodb://simple-micro-mongo-srv:27017/simple-micro'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: simple-micro-srv
spec:
  selector:
    app: simple-micro
  ports:
    - name: simple-micro
      protocol: TCP
      port: 3000
      targetPort: 3000
